language: node_js
node_js:
- '8'
script:
- hexo g
- hexo d
before_install:
- openssl aes-256-cbc -K $encrypted_2719da46c170_key -iv $encrypted_2719da46c170_iv
  -in .travis/github_deploy_key.enc -out ~/.ssh/github_deploy_key -d
- chmod 600 ~/.ssh/github_deploy_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/github_deploy_key
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name '王志文'
- git config --global user.email 'w_angzhiwen@163.com'
addons:
  ssh_known_hosts: 192.30.253.112
